version: "3.8"

services:
  app:
    image: python:3.11-slim
    container_name: expense-tracker-api
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: bash -c "pip install -r requirements.txt && python run.py"

  mongo:
    image: mongo:8.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: expense-tracker-test
    volumes:
      - mongo_data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  mongo_data:
  jenkins_data:
