version: "3.8"

services:
  app:
    image: python:3.11-slim
    container_name: python_app
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - .env
    depends_on:
      - mongo
    command: bash -c "pip install -r requirements.txt && python run.py"

  mongo:
    image: mongo:8.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: expense-tracker-test
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
